### ISSUE TITLE
Failure Writing output to destination

### ISSUE THREAD

**Issue by sheesh12333** [KevCui/animepahe-dl#42]
![image](https://user-images.githubusercontent.com/94157386/141411189-384ae95e-08ce-48d1-8764-1194c062e438.png)
pls help how can I fix this issue

**Comment by KevCui** [comment]
Hi @sheesh12333, I tried to fix this issue in the latest commit. Please pull the changes and let me know if the fix works for you or not. 

If the fix is not working and your issues remains, could you try to download another anime title without flag `-t`? It will help for the investigation. Thanks.

**Comment by sheesh12333** [comment]
I always receive this kind of issue in my old pc. When I download this 2 anime and failed I can't open the folder 'Location is not available'. Then I bought my new pc and download everything, everything seems fine at first then I tried to download 'Tantei wa mou, shindeiru' and it failed so I remember this 2 anime that I wanted to download last time. 
![image](https://user-images.githubusercontent.com/94157386/141602674-1d4899bc-2566-42a9-98ae-c3cc0a80d3e9.png)

**Comment by KevCui** [comment]
Hi @sheesh12333, thanks for the info. It appears that Windows doesn't allow folder name contain trailing dot. I made a fix in the latest commit. If you pull the changes, the issue should be fixed :crossed_fingers:

**Comment by sheesh12333** [comment]
I already executed the first commit and still the same as the first image that I sent

**Comment by KevCui** [comment]
@sheesh12333 Could you please try to download another anime, like: `./animepahe-dl.sh -a 'Steins Gate 0' -e 1`? Does it work for you?

**Comment by KevCui** [comment]
@sheesh12333 From your 2nd screenshot, it shows error "location is not available". I'd assume that the issue you are having is not related to the script itself, it may be caused by the system. It seems that your user account doesn't have the right permission to access to the folder. Could you please grant the permission to your user and double check the permission of the account which is used to run script as well? Let me know if it solves your problem or not. Thanks.

**Comment by sheesh12333** [comment]
The anime that you requested work the character ";" in the anime change to "_''
![image](https://user-images.githubusercontent.com/94157386/142728433-e8d2275e-a7c7-4d25-9314-001ffa1c4d5e.png)

**Comment by sheesh12333** [comment]
I already downloaded a bunch of anime series and I notice that these 3 anime has "." I think my problem is that

**Comment by KevCui** [comment]
@sheesh12333 I think so too. The commit https://github.com/KevCui/animepahe-dl/commit/8364cbc8746f55ec539179fc31fddf330e6e3124 should have replaced the trailing `.` by `_` already. Could you try to download those 3 animes and check the created folders. if they still contain `.`?

**Comment by sheesh12333** [comment]
Hi! I very sorry for replying late I've been busy completing all my midterm requirements and taking exams. I just want you to know that the bug is already fixed, I already try to download the 3 anime with ''.'' today and it's all fine and working. Thank you for helping out!

![image](https://user-images.githubusercontent.com/94157386/144774384-4d0a9bf6-9aea-4a4e-a710-62ae39dfc6c8.png)
![image](https://user-images.githubusercontent.com/94157386/144774444-7c4eff4d-9918-4a5f-863e-45533808bda3.png)
![image](https://user-images.githubusercontent.com/94157386/144774973-7822aa10-5b34-4df5-91ed-c0881bd3a7a8.png)

**Comment by KevCui** [comment]
@sheesh12333 Thanks for checking the fix. Glad that it works out for you. I will then close this issue.
